auth:
  registry.cn-hangzhou.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
  registry.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
images:
  registry.k8s.io/kube-apiserver:latest: registry.aliyuncs.com/wanglulin/kube-apiserver
