auth:
  registry.cn-hangzhou.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
  registry.cn-hangzhou.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
images:
  registry.k8s.io/kube-apiserver:v1.27.1,v1.27.2: registry.aliyuncs.com/wanglulin/kube-apiserver
