name: skopeo
on:
  push:
    branches: [ skopeo-sync ]
  pull_request:
    branches:
      - skopeo-sync
  workflow_dispatch:

env:
  USERNAME: ${{ secrets.ALIYUN_USERNAME }}
  PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: "Skopeo"
      run: |
        # $1=images list, $2=dest registry, $3=namespace
        sh ./sync.sh sync.list registry.cn-hangzhou.aliyuncs.com wanglulin