name: skopeo
on:
  push:
    branches: [ skopeo-sync ]
  pull_request:
    branches:
      - skopeo-sync
  workflow_dispatch:

env:
  USERNAME: ${{ secrets.ALIYUN_USERNAME }}
  PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
  SYNC_LIST:
    - registry.k8s.io/kube-apiserver:v1.27.2 registry.aliyuncs.com/wanglulin

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: "Skopeo"
        run: |    
          echo ${SYNC_LIST}
          skopeo sync --dest-creds ${USERNAME}:${PASSWORD} --src docker --dest docker registry.k8s.io/kube-controller-manager:v1.27.2 registry.aliyuncs.com/wanglulin/