name: skopeo
on:
  push:
    branches: [ skopeo-sync ]
  pull_request:
    branches:
      - skopeo-sync
  workflow_dispatch:

env:
  USERNAME: ${{ secrets.ALIYUN_USERNAME }}
  PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: "Skopeo"
      run: |
        chmod +x ./sync.sh
        sh ./sync.sh