name: skopeo
on:
  push:
    branches: [ skopeo-sync ]
  pull_request:
    branches:
      - skopeo-sync
  workflow_dispatch:

env:
  USERNAME: ${{ secrets.ALIYUN_USERNAME }}
  PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: "Skopeo"
      run: |
        cat sync.list
        while read line ; do skopeo sync --dest-creds ${USERNAME}:${PASSWORD} --src docker --dest docker $line; done < sync.list